
export const GET_HOME_PAGE = "GET_HOME_PAGE"
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST"
export const GET_SUB_CATEGORY_SERVICE = "GET_SUB_CATEGORY_SERVICE"
export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST"
export const GET_STATE_LIST = "GET_STATE_LIST"
export const GET_CITY_LIST = "GET_CITY_LIST"
export const SELLER_SIGN_UP_FORM = "SELLER_SIGN_UP_FORM"
export const USER_SIGN_UP_DETAILS = "USER_SIGN_UP_DETAILS"
export const LOGIN_FORM_DETAILS = "LOGIN_FORM_DETAILS"
export const GET_SERVICE_LIST = "GET_SERVICE_LIST"
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"
export const USER_PROFILE_DETAILS = "USER_PROFILE_DETAILS"
export const USER_GET_WISHLIST = "USER_GET_WISHLIST"
export const GET_SERVICE_DETAILS = "GET_SERVICE_DETAILS"
export const ANOTHER_SERVICE_FROM_SELLER = "ANOTHER_SERVICE_FROM_SELLER"
export const GET_RECOMMENDED_SERVICE_DATA = "GET_RECOMMENDED_SERVICE_DATA"
export const ADD_TO_CART_DETAILS = "ADD_TO_CART_DETAILS"
export const GET_CART_DATA_DETAILS = "GET_CART_DATA_DETAILS"
export const REMOVE_DATA_FROM_CART_DETAILS = "REMOVE_DATA_FROM_CART_DETAILS"
export const CART_UPDATE_PRICE_QUANTITY = "CART_UPDATE_PRICE_QUANTITY"
export const INCREASE_TOTAL_PRICE_CART_PRODUCT = "INCREASE_TOTAL_PRICE_CART_PRODUCT"
export const DECREASE_TOTAL_PRICE_CART_PRODUCT = "DECREASE_TOTAL_PRICE_CART_PRODUCT"

export const SEARCH_GET_SERVICE = "SEARCH_GET_SERVICE"

export const GET_LOCATION_DATA = "GET_LOCATION_DATA"

export const GET_LANGUAGE_DETAILS = "GET_LANGUAGE_DETAILS"

export const GET_LOCAL_LOCAl_STORAGE = "GET_LOCAL_LOCAl_STORAGE"

export const GET_CHECK_AUTH_DETAILS = "GET_CHECK_AUTH_DETAILS"

export const EDIT_USER_PROFILE_DETAILS = "EDIT_USER_PROFILE_DETAILS"

export const GET_STATE_LIST_DETAILS = "GET_STATE_LIST_DETAILS"

export const USER_ADDRESS_DETAILS = "USER_ADDRESS_DETAILS"

export const LIST_USER_ADDRESS_DETAILS = "LIST_USER_ADDRESS_DETAILS"

export const DELETE_USER_ADDRESS_DETAILS = "DELETE_USER_ADDRESS_DETAILS"

export const SINGLE_USER_ADDRESS_DETAILS = "SINGLE_USER_ADDRESS_DETAILS"

export const EDIT_USER_ADDRESS_DETAILS = "EDIT_USER_ADDRESS_DETAILS"

export const START_CONVERSATION_WITH_SELLER_DETAILS = "START_CONVERSATION_WITH_SELLER_DETAILS"

export const USER_CONVERSSATION_NAME = "USER_CONVERSSATION_NAME"

export const USER_CONVERSATION_DETAILS = "USER_CONVERSATION_DETAILS"

export const USER_READ_ALL_CONVERSATION_DETAILS = 'USER_READ_ALL_CONVERSATION_DETAILS'

export const USER_CONVERSATION_LIST_DETAILS = 'USER_CONVERSATION_LIST_DETAILS'

export const USER_MESSAGE_SEND_DETAILS = "USER_MESSAGE_SEND_DETAILS"

export const DELETE_USER_CONVERSATION_MESSAGE_DETAILS = "DELETE_USER_CONVERSATION_MESSAGE_DETAILS"

export const CUSTOMER_SERVICE_INFO = "CUSTOMER_SERVICE_INFO"

export const MENU_BAR_ACTIVE_CLASS_INFO = "MENU_BAR_ACTIVE_CLASS_INFO"

export const GET_REVIEW_RATING_INFO = "GET_REVIEW_RATING_INFO"

export const USER_ADD_REVIEW_RATING_INFO = "USER_ADD_REVIEW_RATING_INFO"